targets:
  $default:
    builders:
      colorist_builder|colorist:
        enabled: true
        generate_for:
          include:
            - lib/**
        options:
          format: true

builders:
  colorist:
    import: "package:colorist_builder/colorist_builder.dart"
    builder_factories: ["coloristBuilder"]
    build_extensions: { ".dart": [".colorist.g.dart"] }
    auto_apply: dependents
    build_to: source
